
CREATE TABLE T_CARGOS(
    ID_CARGO NUMBER NOT NULL,
    NOM_CARGO VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT cargos_pk PRIMARY KEY (ID_CARGO)
);

INSERT INTO T_CARGOS (ID_CARGO, NOM_CARGO) VALUES (0,'AGENTE');
INSERT INTO T_CARGOS (ID_CARGO, NOM_CARGO) VALUES (1,'SUPERAGENTE');
INSERT INTO T_CARGOS (ID_CARGO, NOM_CARGO) VALUES (10,'COORDINADOR/FORMADOR');
INSERT INTO T_CARGOS (ID_CARGO, NOM_CARGO) VALUES (11,'COMUNICACION');
INSERT INTO T_CARGOS (ID_CARGO, NOM_CARGO) VALUES (13,'RECURSOS HUMANOS');
INSERT INTO T_CARGOS (ID_CARGO, NOM_CARGO) VALUES (20,'SUPERVISOR');
INSERT INTO T_CARGOS (ID_CARGO, NOM_CARGO) VALUES (30,'RESPONSABLE');
INSERT INTO T_CARGOS (ID_CARGO, NOM_CARGO) VALUES (90,'ADMINISTRADOR');
INSERT INTO T_CARGOS (ID_CARGO, NOM_CARGO) VALUES (99,'DESARROLLADOR');

SELECT * FROM T_CARGOS ORDER BY ID_CARGO;

DELETE T_CARGOS;

DROP TABLE T_CARGOS;

/*****************************************/

CREATE TABLE T_CIUDADES(
    ID_CIUDAD NUMBER NOT NULL,
    NOM_CIUDAD VARCHAR2(40 BYTE) NOT NULL,
    NOM_PAIS VARCHAR2(30 BYTE) NOT NULL,
    CONSTRAINT ciudades_pk PRIMARY KEY (ID_CIUDAD),
    CONSTRAINT ciudades_uk UNIQUE (NOM_CIUDAD, NOM_PAIS)
);

INSERT INTO T_CIUDADES (ID_CIUDAD, NOM_CIUDAD, NOM_PAIS) VALUES (1,'GUADALAJARA','ESPAÑA');
INSERT INTO T_CIUDADES (ID_CIUDAD, NOM_CIUDAD, NOM_PAIS) VALUES (21,'BOGOTA','COLOMBIA');
INSERT INTO T_CIUDADES (ID_CIUDAD, NOM_CIUDAD, NOM_PAIS) VALUES (42,'BUCARAMANGA','COLOMBIA');
INSERT INTO T_CIUDADES (ID_CIUDAD, NOM_CIUDAD, NOM_PAIS) VALUES (43,'MADRID','ESPAÑA');
INSERT INTO T_CIUDADES (ID_CIUDAD, NOM_CIUDAD, NOM_PAIS) VALUES (65,'OVIEDO','ESPAÑA');
INSERT INTO T_CIUDADES (ID_CIUDAD, NOM_CIUDAD, NOM_PAIS) VALUES (66,'MEDELLIN','COLOMBIA');
INSERT INTO T_CIUDADES (ID_CIUDAD, NOM_CIUDAD, NOM_PAIS) VALUES (67,'LA CORUÑA','ESPAÑA');

SELECT * FROM T_CIUDADES ORDER BY ID_CIUDAD;

DROP TABLE T_CIUDADES;

/*****************************************/

CREATE TABLE T_PLATAFORMAS(
    ID_PLATAFORMA NUMBER NOT NULL,
    NOM_PLATAFORMA VARCHAR2(50 BYTE) NOT NULL,
    ID_CIUDAD NUMBER,
    CONSTRAINT plataformas_pk PRIMARY KEY (ID_PLATAFORMA),
    CONSTRAINT plataformas_uk UNIQUE (NOM_PLATAFORMA, ID_CIUDAD),
    CONSTRAINT plataformas_fk FOREIGN KEY (ID_CIUDAD) REFERENCES T_CIUDADES(ID_CIUDAD)
);

INSERT INTO T_PLATAFORMAS (ID_PLATAFORMA, NOM_PLATAFORMA, ID_CIUDAD) VALUES (1,'JAZZPLAT',1);
INSERT INTO T_PLATAFORMAS (ID_PLATAFORMA, NOM_PLATAFORMA, ID_CIUDAD) VALUES (82,'JAZZPLAT',21);
INSERT INTO T_PLATAFORMAS (ID_PLATAFORMA, NOM_PLATAFORMA, ID_CIUDAD) VALUES (43,'LA FINCA',43);
INSERT INTO T_PLATAFORMAS (ID_PLATAFORMA, NOM_PLATAFORMA, ID_CIUDAD) VALUES (41,'TELEPERFORMANCE',67);
INSERT INTO T_PLATAFORMAS (ID_PLATAFORMA, NOM_PLATAFORMA, ID_CIUDAD) VALUES (81,'TELEPERFORMANCE',66);
INSERT INTO T_PLATAFORMAS (ID_PLATAFORMA, NOM_PLATAFORMA, ID_CIUDAD) VALUES (42,'ARVATO',42);
INSERT INTO T_PLATAFORMAS (ID_PLATAFORMA, NOM_PLATAFORMA, ID_CIUDAD) VALUES (61,'OEST',65);

SELECT * FROM T_PLATAFORMAS ORDER BY ID_PLATAFORMA;

DROP TABLE T_PLATAFORMAS;

/*****************************************/

CREATE TABLE T_USUARIOS(
    NUM_EMPLEADO NUMBER NOT NULL,
    NOM_USUARIO VARCHAR2(70 BYTE) NOT NULL,
    EMAIL VARCHAR2(70 BYTE) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ESTADO NUMBER(1,0) NOT NULL,
    ID_CARGO NUMBER(3,0) NOT NULL,
    ID_PLATAFORMA NUMBER(3,0) NOT NULL,
    CONSTRAINT usuarios_pk PRIMARY KEY (NUM_EMPLEADO),
    CONSTRAINT usuarios_uk UNIQUE (NUM_EMPLEADO, NOM_USUARIO),
    CONSTRAINT usuarios_fk_1 FOREIGN KEY (ID_CARGO) REFERENCES T_CARGOS(ID_CARGO),
    CONSTRAINT usuarios_fk_2 FOREIGN KEY (ID_PLATAFORMA) REFERENCES T_PLATAFORMAS(ID_PLATAFORMA)
);

INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000123,'FRANCISCO ACEDO RIVAS','FACERIV.JGUA@ORANGE.COM',1,0,1); /*AGENTE -- N1 ORANGE, N1 JAZZTEL, FORMACION*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000047,'DIEGO BECERRA MANZANARES','DBECMAN.JGUA@ORANGE.COM',1,0,1); /*AGENTE N1 ORANGE, N1 JAZZTEL*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000212,'JORGE SALGADO SOLTERO','JSALSOL.JGUA@ORANGE.COM',1,1,1); /*SUPERAGENTE N1 ORANGE, N1 JAZZTEL, FORMACION*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000331,'ISABEL RAMOS AUÑÓN','IRAMAUN.JGUA@ORANGE.COM',1,10,1); /*COORDINADOR N1 ORANGE, N1 JAZZTEL*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000012,'SANTIAGO GOMEZ MAYORAL','SGONMAY.JGUA@ORANGE.COM',1,11,1); /*COMUNICACION*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000300,'DAVID WHU CHAO','DWHUCHA.JGUA@ORANGE.COM',1,13,1); /*RECURSOS HUMANOS*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000302,'DAVID MEDIANO SANCHEZ','DMEDSAN.JGUA@ORANGE.COM',1,20,1);/*SUPERVISOR N1 ORANGE, N1 JAZZTEL*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000102,'YEISON CAMILO FIGUEROA','YCAMFIG.JGUA@ORANGE.COM',1,30,1); /*RESPONSABLE N1 ORANGE, N1 JAZZTEL, N2 ORANGE, N2 JAZZTEL*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000450,'ALBERTO PELLITERO DIEZ','APELDIE.JGUA@ORANGE.COM',1,90,1); /*ADMINISTRADOR N1 ORANGE, N1 JAZZTEL, N2 ORANGE, N2 JAZZTEL, SOPORTE INSTALADORES, FORMACIÓN*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000357,'RUBÉN DEL OLMO MORENO','RDELMOR.JGUA@ORANGE.COM',1,99,1); /*DESARROLLADOR N1 ORANGE, N1 JAZZTEL, N2 ORANGE, N2 JAZZTEL, SOPORTE INSTALADORES, FORMACION*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000203,'DIEGO ARGUMEDO BLANDON','DARGBLA.JGUA@ORANGE.COM',1,0,42); /*AGENTE N1 ORANGE, N1 JAZZTEL*/
INSERT INTO T_USUARIOS(NUM_EMPLEADO, NOM_USUARIO, EMAIL, ESTADO, ID_CARGO, ID_PLATAFORMA) VALUES(37000304,'JESICA ORTEGA JARAMILLO','JORTJAR.JGUA@ORANGE.COM',0,0,42); /*AGENTE SIN ACCESO*/

SELECT * FROM T_USUARIOS ORDER BY NUM_EMPLEADO;

DROP TABLE T_USUARIOS;

/*****************************************/

CREATE TABLE T_CONFIGURACION(
    NUM_EMPLEADO NUMBER NOT NULL,
    LOGIN VARCHAR2(14 CHAR) NOT NULL,
    AVATAR VARCHAR2(1000 CHAR),
    ACCEDE_CHAT VARCHAR2(2 CHAR) NOT NULL,
    CONTRASENIA VARCHAR2(70 BYTE) NOT NULL,
    CONSTRAINT configuracion_pk PRIMARY KEY (NUM_EMPLEADO),
    CONSTRAINT configuracion_uk UNIQUE (LOGIN),
    CONSTRAINT configuracion_fk FOREIGN KEY (NUM_EMPLEADO) REFERENCES T_USUARIOS(NUM_EMPLEADO)
);

INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000123,'FACERIV','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000047,'DBECMAN','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000212,'JSALSOL','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000331,'IRAMAUN','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000012,'SGONMAY','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000300,'DWHUCHA','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000302,'DMEDSAN','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000102,'YCAMFIG','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000450,'APELDIE','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000357,'RDELMOR','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000203,'DARGBLA','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');
INSERT INTO T_CONFIGURACION (NUM_EMPLEADO, LOGIN, ACCEDE_CHAT, CONTRASENIA) VALUES (37000304,'JORTJAR','SI','01156af4d71824313244b23cceffe938337a4b49d8ad09e40f81f890e62396ad');

SELECT * FROM T_CONFIGURACION ORDER BY NUM_EMPLEADO;

DROP TABLE T_CONFIGURACION;

/*****************************************/

CREATE TABLE T_TOKENS_AUX(
    TOKEN VARCHAR2(60 CHAR),
    LOGIN VARCHAR2(14 CHAR),
    FECHA_EXPIRACION NUMBER,
    ESTADO VARCHAR2(60 CHAR),
    SOCKET VARCHAR2(100 CHAR),
    CONSTRAINT tokens_pk PRIMARY KEY (TOKEN),
    CONSTRAINT tokens_fk FOREIGN KEY (LOGIN) REFERENCES T_CONFIGURACION(LOGIN)
);

SELECT * FROM T_TOKENS_AUX ORDER BY TOKEN;

DELETE T_TOKENS_AUX;

DROP TABLE T_TOKENS_AUX;

/*****************************************/

CREATE TABLE T_SERVICIOS(
    ID_SERVICIO NUMBER NOT NULL,
    NOM_SERVICIO VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT servicios_pk PRIMARY KEY (ID_SERVICIO),
    CONSTRAINT servicios_uk UNIQUE (NOM_SERVICIO)
);

INSERT INTO T_SERVICIOS (ID_SERVICIO, NOM_SERVICIO) VALUES (1,'BACKOFFICE N2 ORANGE');
INSERT INTO T_SERVICIOS (ID_SERVICIO, NOM_SERVICIO) VALUES (11,'BACKOFFICE N2 JAZZTEL');
INSERT INTO T_SERVICIOS (ID_SERVICIO, NOM_SERVICIO) VALUES (21,'TECNICO N1 FIJO ORANGE');
INSERT INTO T_SERVICIOS (ID_SERVICIO, NOM_SERVICIO) VALUES (31,'TECNICO N1 FIJO JAZZTEL');
INSERT INTO T_SERVICIOS (ID_SERVICIO, NOM_SERVICIO) VALUES (41,'SOPORTE INSTALADORES');
INSERT INTO T_SERVICIOS (ID_SERVICIO, NOM_SERVICIO) VALUES (51,'FORMACION');
INSERT INTO T_SERVICIOS (ID_SERVICIO, NOM_SERVICIO) VALUES (62,'DESARROLLO');

SELECT * FROM T_SERVICIOS ORDER BY ID_SERVICIO;

DROP TABLE T_SERVICIOS;

/*****************************************/

/*
create or replace TRIGGER TR_ID_SALAS 
BEFORE INSERT ON T_SALAS
FOR EACH ROW
BEGIN
  IF :new.ID_SALA IS NULL THEN
    SELECT SQ_ID_SALAS.NEXTVAL
    INTO :new.ID_SALA
    FROM dual;
  END IF;
END;
*/

CREATE SEQUENCE sq_id_salas INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 9999 CACHE 10;

CREATE TABLE T_SALAS(
    ID_SALA NUMBER,
    NOMBRE_SALA VARCHAR2(200 CHAR) NOT NULL,
    ACTIVA VARCHAR2(2 CHAR) NOT NULL,
    TIPO VARCHAR2(100 CHAR) NOT NULL,
    CREADOR VARCHAR2(50 CHAR),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    CONSTRAINT salas_pk PRIMARY KEY (ID_SALA)
);

INSERT INTO T_SALAS (ID_SALA, NOMBRE_SALA, ACTIVA, TIPO) VALUES (1,'BACKOFFICE N2 ORANGE','SI','SERVICIO');
INSERT INTO T_SALAS (ID_SALA, NOMBRE_SALA, ACTIVA, TIPO) VALUES (11,'BACKOFFICE N2 JAZZTEL','SI','SERVICIO');
INSERT INTO T_SALAS (ID_SALA, NOMBRE_SALA, ACTIVA, TIPO) VALUES (21,'TECNICO N1 FIJO ORANGE','SI','SERVICIO');
INSERT INTO T_SALAS (ID_SALA, NOMBRE_SALA, ACTIVA, TIPO) VALUES (31,'TECNICO N1 FIJO JAZZTEL','SI','SERVICIO');
INSERT INTO T_SALAS (ID_SALA, NOMBRE_SALA, ACTIVA, TIPO) VALUES (41,'SOPORTE INSTALADORES','SI','SERVICIO');
INSERT INTO T_SALAS (ID_SALA, NOMBRE_SALA, ACTIVA, TIPO) VALUES (51,'FORMACION','SI','SERVICIO');
INSERT INTO T_SALAS (ID_SALA, NOMBRE_SALA, ACTIVA, TIPO) VALUES (62,'DESARROLLO','SI','SERVICIO');
INSERT INTO T_SALAS (ID_SALA, NOMBRE_SALA, ACTIVA, TIPO) VALUES (301,'COMUNICACIÓN','SI','COMUN');
INSERT INTO T_SALAS (ID_SALA, NOMBRE_SALA, ACTIVA, TIPO) VALUES (302,'RECURSOS HUMANOS','SI','COMUN');

SELECT * FROM T_SALAS ORDER BY ID_SALA;

DELETE T_SALAS;

DROP TABLE T_SALAS;

/*****************************************/

CREATE TABLE T_ROLES_USUARIOS(
    LOGIN VARCHAR2(20 CHAR) NOT NULL,
    ID_SALA NUMBER NOT NULL,
    ROL VARCHAR2(30 CHAR),
    ACTIVO VARCHAR2(10 CHAR),
    CONSTRAINT rolesusuarios_pk PRIMARY KEY (LOGIN, ID_SALA),
    CONSTRAINT rolesusuarios_fk_1 FOREIGN KEY (ID_SALA) REFERENCES T_SALAS(ID_SALA),
    CONSTRAINT rolesusuarios_fk_2 FOREIGN KEY (LOGIN) REFERENCES T_CONFIGURACION(LOGIN)
);

INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('FACERIV',21,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('FACERIV',31,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('FACERIV',51,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('FACERIV',301,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('FACERIV',302,'A1','SI');

INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DBECMAN',21,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DBECMAN',31,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DBECMAN',301,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DBECMAN',302,'A1','SI');


INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('JSALSOL',21,'A2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('JSALSOL',31,'A2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('JSALSOL',51,'A2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('JSALSOL',301,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('JSALSOL',302,'A1','SI');


INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('IRAMAUN',21,'C1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('IRAMAUN',31,'C1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('IRAMAUN',301,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('IRAMAUN',302,'A1','SI');

INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('SGONMAY',301,'C2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('SGONMAY',302,'A1','SI');

INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DWHUCHA',301,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DWHUCHA',302,'C3','SI');

INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DMEDSAN',21,'S1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DMEDSAN',31,'S1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DMEDSAN',301,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DMEDSAN',302,'A1','SI');

INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('YCAMFIG',1,'R1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('YCAMFIG',11,'R1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('YCAMFIG',21,'R1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('YCAMFIG',31,'R1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('YCAMFIG',301,'R1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('YCAMFIG',302,'R1','SI');

INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('APELDIE',1,'Z1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('APELDIE',11,'Z1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('APELDIE',21,'Z1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('APELDIE',31,'Z1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('APELDIE',41,'Z1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('APELDIE',51,'Z1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('APELDIE',301,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('APELDIE',302,'A1','SI');

INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('RDELMOR',1,'Z2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('RDELMOR',11,'Z2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('RDELMOR',21,'Z2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('RDELMOR',31,'Z2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('RDELMOR',41,'Z2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('RDELMOR',51,'Z2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('RDELMOR',62,'A2','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('RDELMOR',301,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('RDELMOR',302,'A1','SI');

INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DARGBLA',1,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DARGBLA',11,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DARGBLA',301,'A1','SI');
INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('DARGBLA',302,'A1','SI');

/*INSERT INTO T_ROLES_USUARIOS (LOGIN, ID_SALA, ROL, ACTIVO) VALUES ('',,'','SI');*/

SELECT * FROM T_ROLES_USUARIOS ORDER BY LOGIN;

DROP TABLE T_ROLES_USUARIOS;

/*****************************************/

CREATE SEQUENCE sq_mensajes_chat INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE TABLE T_MENSAJES(
    ID_MENSAJE NUMBER DEFAULT "SQ_MENSAJES_CHAT"."NEXTVAL" NOT NULL,
    LOGIN_EMISOR VARCHAR2(20 CHAR),
    NOMBRE VARCHAR2(100 CHAR),
    DEPARTAMENTO VARCHAR2(100 CHAR),
    LOGIN_RECEPTOR VARCHAR2(20 CHAR),
    FECHA_MS NUMBER DEFAULT to_number(SYSDATE - TO_DATE('01-01-1970','DD-MM-YYYY')) * (24 * 60 * 60 * 1000),
    MENSAJE VARCHAR2(500 CHAR),
    ID_ANTERIOR NUMBER,
    ID_INICIAL NUMBER,
    FECHA_DATE DATE DEFAULT SYSDATE,
    ETIQUETAS VARCHAR2(400 BYTE),
    SALA NUMBER,
    REACCIONES VARCHAR2(400 BYTE),
    ID_PLATAFORMA NUMBER,
    CONSTRAINT mensajes_pk PRIMARY KEY (ID_MENSAJE)
);

SELECT * FROM T_MENSAJES;

DELETE T_MENSAJES;

DROP TABLE T_MENSAJES;

/*****************************************/

CREATE TABLE T_ESTADO_MENSAJES(
    ID_MENSAJE NUMBER NOT NULL,
    ESTADO VARCHAR2(50 CHAR),
    TIPO VARCHAR2(50 CHAR),
    LOGIN VARCHAR2(20 CHAR),
    ESTADO_ID NUMBER NOT NULL,
    FECHA DATE DEFAULT SYSDATE,
    ID_SALA NUMBER,
    CONSTRAINT estadoMensajes_pk PRIMARY KEY (ID_MENSAJE, LOGIN, ESTADO_ID, FECHA),
    CONSTRAINT estadoMensajes_fk_1 FOREIGN KEY(ID_MENSAJE) REFERENCES T_MENSAJES(ID_MENSAJE),
    CONSTRAINT estadoMensajes_fk_2 FOREIGN KEY(LOGIN) REFERENCES T_CONFIGURACION(LOGIN)
);

SELECT * FROM T_ESTADO_MENSAJES;

DELETE T_ESTADO_MENSAJES;

DROP TABLE T_ESTADO_MENSAJES;

/*****************************************/

CREATE VIEW V_LOGIN AS (
SELECT TUSU.NUM_EMPLEADO, TCON.LOGIN, TUSU.NOM_USUARIO, TUSU.ESTADO, TUSU.EMAIL, TUSU.FECHA_CREACION,
       TCAR.NOM_CARGO, TCON.AVATAR, TCON.CONTRASENIA, TPLAT.NOM_PLATAFORMA, TCIU.NOM_CIUDAD, TCIU.NOM_PAIS,
       LISTAGG((SELECT NOM_SERVICIO FROM T_SERVICIOS TSER WHERE TSER.ID_SERVICIO = TRUSU.ID_SALA),', ') WITHIN GROUP (ORDER BY TRUSU.ID_SALA) AS "SERVICIOS"
FROM T_USUARIOS TUSU
INNER JOIN T_CONFIGURACION TCON ON TCON.NUM_EMPLEADO = TUSU.NUM_EMPLEADO
INNER JOIN T_ROLES_USUARIOS TRUSU ON TCON.LOGIN = TRUSU.LOGIN
INNER JOIN T_CARGOS TCAR ON TCAR.ID_CARGO = TUSU.ID_CARGO
INNER JOIN T_PLATAFORMAS TPLAT ON TPLAT.ID_PLATAFORMA = TUSU.ID_PLATAFORMA
INNER JOIN T_CIUDADES TCIU ON TCIU.ID_CIUDAD = TPLAT.ID_CIUDAD
GROUP BY  TUSU.NUM_EMPLEADO, TCON.LOGIN, TUSU.NOM_USUARIO, TUSU.ESTADO, TUSU.EMAIL, TUSU.FECHA_CREACION,
       TCAR.NOM_CARGO, TCON.AVATAR, TCON.CONTRASENIA, TPLAT.NOM_PLATAFORMA, TCIU.NOM_CIUDAD, TCIU.NOM_PAIS);
       
SELECT * FROM V_LOGIN;
       
DROP VIEW V_LOGIN;

/*****************************************/

CREATE VIEW V_MENSAJES_CHAT AS (
SELECT MENSAJES.ID_MENSAJE as "messageId", MENSAJES.SALA as "roomId", MENSAJES.LOGIN_EMISOR as "emitter", MENSAJES.NOMBRE as "name",
       MENSAJES.ID_PLATAFORMA as "platformId", MENSAJES.LOGIN_RECEPTOR as "receiver", MENSAJES.FECHA_DATE as "date", MENSAJES.MENSAJE as "message",
       MENSAJES.ETIQUETAS as "labels", MENSAJES.ID_ANTERIOR as "previousId", TCONF.AVATAR as "avatar", H_MENSAJES.H_LOGIN as "previousLOGIN", H_MENSAJES.H_NOMBRE as "previousUserName",
       H_MENSAJES.H_MENSAJE as "previousMessage", R_USUARIOS.ROL as "role", ESTADOS.LASTSTATE as "lastState", ESTADOS.STATEDATE as "stateDate", ESTADOS.LOGIN as "stateLOGIN"
FROM 
    T_MENSAJES MENSAJES
INNER JOIN 
    T_ROLES_USUARIOS R_USUARIOS ON R_USUARIOS.LOGIN = MENSAJES.LOGIN_EMISOR AND R_USUARIOS.ID_SALA = MENSAJES.SALA
LEFT JOIN 
    (SELECT ID_MENSAJE AS HID_MENSAJE, LOGIN_EMISOR AS H_LOGIN, NOMBRE AS H_NOMBRE, MENSAJE AS H_MENSAJE FROM T_MENSAJES) H_MENSAJES
    ON H_MENSAJES.HID_MENSAJE = MENSAJES.ID_ANTERIOR
LEFT JOIN
    (SELECT ID_MENSAJE, LOGIN, ESTADO_ID AS LASTSTATE, FECHA AS STATEDATE
    FROM T_ESTADO_MENSAJES t1 WHERE FECHA = (SELECT MAX(FECHA)
        FROM T_ESTADO_MENSAJES t2 WHERE t1.ID_MENSAJE = t2.ID_MENSAJE)
    ) ESTADOS
    ON ESTADOS.ID_MENSAJE = MENSAJES.ID_MENSAJE
LEFT JOIN
    (SELECT LOGIN, AVATAR FROM T_CONFIGURACION) TCONF
    ON TCONF.LOGIN = MENSAJES.LOGIN_EMISOR
);

SELECT * FROM V_MENSAJES_CHAT;

DROP VIEW V_MENSAJES_CHAT;

/*****************************************/

SELECT LOGIN, ROL, NOMBRE_SALA 
FROM T_ROLES_USUARIOS roles,T_SALAS salas
WHERE  roles.ID_SALA = salas.ID_SALA
ORDER BY LOGIN;


/*****************************************/


/*****************************************/


/*****************************************/


/*****************************************/


/*****************************************/

